### ISSUE TITLE
Rollup-executor queries hit potentially-undefined behavior?

### ISSUE THREAD

**Issue by speezepearson** [ArpNetworking/metrics-portal#350]
- [`RollupExecutor` appears to set both `align_sampling` and `align_start_time`](https://github.com/ArpNetworking/metrics-portal/blob/a13645a89655603233444970748bdedec12e8feb/app/com/arpnetworking/rollups/RollupExecutor.java#L120)
- [the docs say](https://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html#metric-properties) that "align_sampling and align_start_time are mutually exclusive. If more than one are set, unexpected results will occur."

@ddimensia might know offhand why these are both set, what the semantics of each are, and which one we really want? If not, I'll look into it.

**Comment by ddimensia** [comment]
Yeah, if you read the KairosDB source you'll find that they're independent of one another.  By combining them you get what we call 'Period' alignment.  

`align_sampling` causes the query engine to zero out the minutes/seconds/etc..  (based on sampling time unit) of the requested start of the query range.  Effectively it moves the start of the range to the earliest sample aligned point.

`align_start_time` causes the timestamps of datapoints returned by Kairos to be rewritten so that they match the start of the sampling unit the range aggregator operated over.  By default, Kairos returns the timestamp as the first timestamp seen in the range.  If you're guaranteed to see a datapoint every second then you'd always get one at the start of the period but for sparse metrics that isn't necessarily so. 

Since one effects the data selected that feeds into the Range aggregator and the other effects the timestamp of the aggregated data they're somewhat independent.  If you set align_start_time and didn't set align_sampling I could see an issue, this may cause a resulting aggregate value to include data from what is effectively the following period.

**Comment by speezepearson** [comment]
Ah, so `align_sampling` aligns the aggregation-period boundaries to the wall clock, while `align_start_time` sets each aggregation-period's datapoint's timestamp to the period's start. So setting both those flags sets each aggregation-period's datapoint's timestamp to be wall-clock-aligned.

So, if I have a metric with exactly one sample, at 01:30:00...
```
~ $ curl -XPOST http://localhost:8080/api/v1/datapoints --data-binary "$(jq -n '[{name:"foo", tags:{a:"a"}, datapoints: [[("2020-04-01T01:30:00Z"|fromdate*1000), 1]]}]')"
```
...and I query it starting at 00:15:00...
```
~ $ for align_start_time in true false; do for align_sampling in true false; do echo "align_start_time=$align_start_time, align_sampling=$align_sampling"; curl --silent -XPOST http://localhost:8080/api/v1/datapoints/query --data-binary "$(jq -n '{start_absolute: ("2020-04-01T00:15:00Z"|fromdate*1000), metrics:[{name:"foo", aggregators:[{name:"count", align_start_time: '$align_start_time', align_sampling: '$align_sampling', sampling:{value:1,unit:"hours"}}]}]}')" | jq '.queries[].results[].values[][0] | ./1000 | todate'; done; done
```
...then I will see timestamp `01:30:00` unless I set `align_start_time`; and then I will see `01:15:00` (i.e. exactly 1h after the query start) unless I also set `align_sampling`; and then I will see `01:00:00`.
```
align_start_time=true, align_sampling=true
"2020-04-01T01:00:00Z"
align_start_time=true, align_sampling=false
"2020-04-01T01:15:00Z"
align_start_time=false, align_sampling=true
"2020-04-01T01:30:00Z"
align_start_time=false, align_sampling=false
"2020-04-01T01:30:00Z"
```

Makes sense! Thanks!
